swagger: '2.0'
info:
  title: Bank Argent transactions API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - User Module
      summary: Get user transactions
      description: API for getting all transactions for the logged in user
      parameters:
        - in: path
          name: timespan
          description: The period of time for which the transactions are to be fetched, in the format YYYY/MM/DD-YYYY/MM/DD, the current month transactions will be return if not provided. e.g. 2021/01/01-2021/01/31
          type: string
          required: false
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Successfully got user Accounts-listing
          schema:
            $ref: '#/definitions/UserTransactionsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Expired or Invalid Token
        '500':
          description: Internal Server Error
    post:
      tags:
        - User Module
      summary: Create a new transaction
      description: API for creating a new transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Create a new transaction
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Successfully created a new transaction
          schema:
            $ref: '#/definitions/UserTransactionDetailResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Expired or Invalid Token
        '500':
          description: Internal Server Error
  /user/transactions/{id}:
    get:
      tags:
        - User Module
      summary: Get a user transaction details
      description: API for getting a transaction details for the logged in user
      parameters:
        - in: path
          name: id
          description: The ID of the transaction to retrieve
          type: string
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Successfully got user Accounts-listing
          schema:
            $ref: '#/definitions/UserTransactionDetailResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Expired or Invalid Token
        '500':
          description: Internal Server Error
    put:
      responses:
        '200':
          description: Successfully updated user Accounts-listing
          schema:
            $ref: '#/definitions/UpdateTransactionsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Expired or Invalid Token
        '500':
          description: Internal Server Error
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: Update a user transaction
      description: API for updating a user transaction
      parameters:
        - in: path
          name: id
          description: The ID of the transaction to update
          type: string
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
    delete:
      responses:
        '200':
          description: Successfully deleted user transaction
          schema:
            $ref: '#/definitions/DeleteTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Expired or Invalid Token
        '500':
          description: Internal Server Error
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: Delete a user transaction
      description: API for deleting a user transaction
      parameters:
        - in: path
          name: id
          description: The ID of the transaction to delete
          type: string
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UserTransactionDetailResponse:
    items:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        title:
          type: string
        description:
          type: string
        amount:
          type: number
        newBalance:
          type: number
        type:
          type: string
        category:
          type: string
        notes:
          type: string
        "__v":
          type: number
  UserTransactionsResponse:
    items:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        title:
          type: string
        description:
          type: string
        amount:
          type: number
        newBalance:
          type: number
  NewTransaction:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      amount:
        type: number
      newBalance:
        type: number
      category:
        type: string
      notes:
        type: string
  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  UpdateTransactionsResponse:
    type: object
    properties:
      _id:
        type: string
      userId:
        type: string
      title:
        type: string
      description:
        type: string
      amount:
        type: number
      newBalance:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string
      "__v":
        type: number
  DeleteTransactionResponse:
    type: object
    properties:
      _id:
        type: string
      title:
        type: string
      amount:
        type: number
  DeleteTransaction:
    type: object
    properties:
      _id:
        type: string
